name: 'fluxcd-kustomize-check'
description: 'check fluxcd and kustomize folder'
inputs:
  check-paths:
    description: 'One or space separated path definitions'
    required: true
  kustomize-version:
    description: 'Version of kustomize to install'
    required: false
    default: 'latest'
  kubeconform-version:
    description: 'Version of kubeconform to install'
    required: false
    default: 'latest'
  yq-version:
    description: 'Version of yq to install'
    required: false
    default: 'latest'
  no-check:
    description: 'Only install tools, no check'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Install Tools
      env:
        KUBECONFORM_VERSION: ${{ inputs.kubeconform-version }}
        KUSTOMIZE_VERSION: ${{ inputs.kustomize-version }}
        YQ_VERSION: ${{ inputs.yq-version }}
      run: ${{ github.action_path }}/scripts/install_tools.sh
      shell: bash
    - name: Run Check
      run: ${{ github.action_path }}/scripts/validate.sh ${{ inputs.check-paths }}
      shell: bash
      if: ${{ inputs.no-check != 'true' }}
